### ISSUE TITLE
Data Set Required

### ISSUE THREAD

**Issue by MaheshtheDev** [ashishtele/Spotify-s-Worldwide-Daily-Song-Ranking#1]
Can you upload Data Set that used in this Project.

**Comment by ashishtele** [comment]
Hi Mahesh, The file is 360MB big. Github is not allowing it.

**Comment by MaheshtheDev** [comment]
> Hi Mahesh, The file is 360MB big. Github is not allowing it.

Share the link of site where you find this Data Set.
